development:
  adapter: postgresql
  encoding: utf8
  database: ihome_development
  username: postgres
  password: postgres.s
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: ihome_production
  username: postgres
  password: postgres.s
  host: localhost
